sudo: required

language: generic

env:
  global:
      - secure: MOYYuw2rdEnZX8vD40suPzeRfHNZXbBPlnkvFjgL6oEM5szIRMPUrvoCGHpg2hKaUjLL+zwvWXq0JUfnceC8CVxXPhQ7QH19cKaT7sxNSKVyqCvDZI9uCfOUGimtUOffdM8ASd13LoNBu64pqocL/AbksizZzkttFQT/BQBgQ/H4K+lLvEktvgPs6vMrTD+HXEx6JFbY1xEp6DR7RKivjRUdoOiWq/IQuRuBcc6C1iwVZWRUJ4WjND4ijACblJwao8lq20rImfjCtiJS27zezWIOW1BIJpxa3HPmB0apcMjTadG3Pdt47d8cWtMQXGFtWcysXhog6rlPkIXWdEbFxs0abzAxdifslgbEKY6A3i3KVSo/x6asCS1GlqRrueE6XPOetKqtU9KKxy2GW4HUYnhBISsuQc8ETJYDW9KxObGDYo5oruI21tK1YxbD9tvM237z86JzVWfNZ9BraR+lymwYwyeYAzAzdG5PO6vtB90Jo2fmF8IAGRmomd2E7ua9g2j3LkYEACTtmjfzufk8Tg9bewNQX+e1CBknlsDPwnamPoWeCAi+oY8/HgM2/kmnZUdcD0P4trEjxAblp1FU4h/90VL5MZjJSwUTwMXWjKYA7sEKPNl+U7xmAIweAFtrBGYLjXWVLAyX3cifbRxdxTNarAxvfwLL1+iq/jaUQ2c=
      - secure: HoIoctbRiJuYUVaN2bjy5UuPku6qVCBCDxWetMJdg4ZsjDXKZhJavNXakN/stLTBQeTR9w0jJk+dT8i7evEtiC7EsTPSpks8iggpe+XVbFXdg4dqC0PqNu6iSOxANSjRfowtqasrSqddWfsqNdOVm1VVP1Ft3VGaQTOdmkApOT1TTCQngM+ji5D88OnOdNowIvdVX87ki1LwRhfFOLYkOsistkhBWmxICRCFwQ8zlMYsBhHXzTSPl6u01sMn2zO/8pp38UzZ0wcbZb1Oe3HvxCL+5Vzkqw7/bUwO1YMWt1nHKIL7rdy5PzolsOlFG7aoYoU2XAVmWM79x8D1LHS+MwPO6Gaf1zRlTDZiHQC174vf4TQegndOhqkRMk8sBOrRMxNzh7ugbVE7yX3yFfMQ/fUXKwUHv2+EJBzaDpnxplvFvFCW/EDce1fPD4WYd6eYFLnDk5DtwCfbmjPfzA6swdz6Nadq1u52HIPcAhrsBwq4GjIiEj1o7vDvadsUmV0BrDouwjTRy+EQ+VhbUPL6pJ0suYtTBKvulk/h14onVSKxLEn9PEUMTCdMyi9RqwffeAytgRA6yxzSNOOl3f4sQU4bGK878OqqpWymYCO3TukuF9/fZemcO/I/XtjKoqhXG4DevsUuimBShQh1iC5ca6IYShp5lrXlSDS2L6rwwC0=

services:
  - docker

before_install:
  - docker login -u="$DOCKERUSER" -p="$DOCKERPASS"

install:
  - travis_wait 30 docker build -t jcpaiva/apicy:base .
  - chmod +x generate-variants.sh
  - bash generate-variants.sh
  - travis_wait 30 docker build -t jcpaiva/apicy:da    -f build/da/Dockerfile    .
  - travis_wait 30 docker build -t jcpaiva/apicy:da_lg -f build/da/Dockerfile.lg .
  - travis_wait 30 docker build -t jcpaiva/apicy:da_md -f build/da/Dockerfile.md .
  - travis_wait 30 docker build -t jcpaiva/apicy:de    -f build/de/Dockerfile    .
  - travis_wait 30 docker build -t jcpaiva/apicy:de_lg -f build/de/Dockerfile.lg .
  - travis_wait 30 docker build -t jcpaiva/apicy:de_md -f build/de/Dockerfile.md .
  - travis_wait 30 docker build -t jcpaiva/apicy:el    -f build/el/Dockerfile    .
  - travis_wait 30 docker build -t jcpaiva/apicy:el_lg -f build/el/Dockerfile.lg .
  - travis_wait 30 docker build -t jcpaiva/apicy:el_md -f build/el/Dockerfile.md .
  - travis_wait 30 docker build -t jcpaiva/apicy:en    -f build/en/Dockerfile    .
  - travis_wait 30 docker build -t jcpaiva/apicy:en_lg -f build/en/Dockerfile.lg .
  - travis_wait 30 docker build -t jcpaiva/apicy:en_md -f build/en/Dockerfile.md .
  - travis_wait 30 docker build -t jcpaiva/apicy:es    -f build/es/Dockerfile    .
  - travis_wait 30 docker build -t jcpaiva/apicy:es_lg -f build/es/Dockerfile.lg .
  - travis_wait 30 docker build -t jcpaiva/apicy:es_md -f build/es/Dockerfile.md .
  - travis_wait 30 docker build -t jcpaiva/apicy:fr    -f build/fr/Dockerfile    .
  - travis_wait 30 docker build -t jcpaiva/apicy:fr_lg -f build/fr/Dockerfile.lg .
  - travis_wait 30 docker build -t jcpaiva/apicy:fr_md -f build/fr/Dockerfile.md .
  - travis_wait 30 docker build -t jcpaiva/apicy:it    -f build/it/Dockerfile    .
  - travis_wait 30 docker build -t jcpaiva/apicy:it_lg -f build/it/Dockerfile.lg .
  - travis_wait 30 docker build -t jcpaiva/apicy:it_md -f build/it/Dockerfile.md .
  - travis_wait 30 docker build -t jcpaiva/apicy:lt    -f build/lt/Dockerfile    .
  - travis_wait 30 docker build -t jcpaiva/apicy:lt_lg -f build/lt/Dockerfile.lg .
  - travis_wait 30 docker build -t jcpaiva/apicy:lt_md -f build/lt/Dockerfile.md .
  - travis_wait 30 docker build -t jcpaiva/apicy:nb    -f build/nb/Dockerfile    .
  - travis_wait 30 docker build -t jcpaiva/apicy:nb_lg -f build/nb/Dockerfile.lg .
  - travis_wait 30 docker build -t jcpaiva/apicy:nb_md -f build/nb/Dockerfile.md .
  - travis_wait 30 docker build -t jcpaiva/apicy:nl    -f build/nl/Dockerfile    .
  - travis_wait 30 docker build -t jcpaiva/apicy:nl_lg -f build/nl/Dockerfile.lg .
  - travis_wait 30 docker build -t jcpaiva/apicy:nl_md -f build/nl/Dockerfile.md .
  - travis_wait 30 docker build -t jcpaiva/apicy:pl    -f build/pl/Dockerfile    .
  - travis_wait 30 docker build -t jcpaiva/apicy:pl_lg -f build/pl/Dockerfile.lg .
  - travis_wait 30 docker build -t jcpaiva/apicy:pl_md -f build/pl/Dockerfile.md .
  - travis_wait 30 docker build -t jcpaiva/apicy:pt    -f build/pt/Dockerfile    .
  - travis_wait 30 docker build -t jcpaiva/apicy:pt_lg -f build/pt/Dockerfile.lg .
  - travis_wait 30 docker build -t jcpaiva/apicy:pt_md -f build/pt/Dockerfile.md .
  - travis_wait 30 docker build -t jcpaiva/apicy:ro    -f build/ro/Dockerfile    .
  - travis_wait 30 docker build -t jcpaiva/apicy:ro_lg -f build/ro/Dockerfile.lg .
  - travis_wait 30 docker build -t jcpaiva/apicy:ro_md -f build/ro/Dockerfile.md .
  - travis_wait 30 docker build -t jcpaiva/apicy:all   -f build/all/Dockerfile   .
after_success:
  - docker push jcpaiva/apicy:base
  - docker push jcpaiva/apicy:da
  - docker push jcpaiva/apicy:da_lg
  - docker push jcpaiva/apicy:da_md
  - docker push jcpaiva/apicy:de
  - docker push jcpaiva/apicy:de_lg
  - docker push jcpaiva/apicy:de_md
  - docker push jcpaiva/apicy:el
  - docker push jcpaiva/apicy:el_lg
  - docker push jcpaiva/apicy:el_md
  - docker push jcpaiva/apicy:en
  - docker push jcpaiva/apicy:en_lg
  - docker push jcpaiva/apicy:en_md
  - docker push jcpaiva/apicy:es
  - docker push jcpaiva/apicy:es_lg
  - docker push jcpaiva/apicy:es_md
  - docker push jcpaiva/apicy:fr
  - docker push jcpaiva/apicy:fr_lg
  - docker push jcpaiva/apicy:fr_md
  - docker push jcpaiva/apicy:it
  - docker push jcpaiva/apicy:it_lg
  - docker push jcpaiva/apicy:it_md
  - docker push jcpaiva/apicy:lt
  - docker push jcpaiva/apicy:lt_lg
  - docker push jcpaiva/apicy:lt_md
  - docker push jcpaiva/apicy:nb
  - docker push jcpaiva/apicy:nb_lg
  - docker push jcpaiva/apicy:nb_md
  - docker push jcpaiva/apicy:nl
  - docker push jcpaiva/apicy:nl_lg
  - docker push jcpaiva/apicy:nl_md
  - docker push jcpaiva/apicy:pl
  - docker push jcpaiva/apicy:pl_lg
  - docker push jcpaiva/apicy:pl_md
  - docker push jcpaiva/apicy:pt
  - docker push jcpaiva/apicy:pt_lg
  - docker push jcpaiva/apicy:pt_md
  - docker push jcpaiva/apicy:ro
  - docker push jcpaiva/apicy:ro_lg
  - docker push jcpaiva/apicy:ro_md
  - docker push jcpaiva/apicy:all
